import { Project, Category } from './types';

export const CATEGORIES: Category[] = [
  'Mobile App',
  'Web App',
  'Website',
  'AI',
  'SaaS',
  'E-commerce',
];

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Dating App - HeartPulse',
    shortDescription: 'Connect with people based on shared values and authentic interests.',
    fullDescription: 'HeartPulse is a revolutionary dating platform designed for genuine connections. It features real-time matchmaking, secure video calls, and a personality-driven matching algorithm that moves beyond superficial swipes.',
    thumbnail: 'https://picsum.photos/seed/dating/800/600',
    gallery: [
      'https://picsum.photos/seed/dating1/800/600',
      'https://picsum.photos/seed/dating2/800/600',
    ],
    demoUrl: 'https://example.com/demo/dating',
    liveUrl: 'https://heartpulse.app',
    category: 'Mobile App',
    tags: ['React Native', 'Firebase', 'Matchmaking'],
    techStack: ['React Native', 'Expo', 'Firestore', 'Tailwind', 'Node.js'],
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Global E-commerce Dashboard',
    shortDescription: 'High-performance e-commerce solution for scale.',
    fullDescription: 'A full-stack e-commerce solution featuring a blazing-fast storefront and a robust inventory management dashboard. Optimized for 100k+ SKUs and global delivery tracking.',
    thumbnail: 'https://picsum.photos/seed/shop/800/600',
    gallery: [
      'https://picsum.photos/seed/shop1/800/600',
      'https://picsum.photos/seed/shop2/800/600',
    ],
    liveUrl: 'https://globalshop.io',
    category: 'Web App',
    tags: ['Next.js', 'Stripe', 'Redis'],
    techStack: ['Next.js', 'Typescript', 'Stripe API', 'Redis', 'Tailwind CSS'],
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Lumina AI - Image Generator',
    shortDescription: 'Convert text to breathtaking visuals with advanced diffusion models.',
    fullDescription: 'Lumina AI leverages powerful machine learning models to generate high-resolution artistic assets from simple natural language prompts. Perfect for designers and content creators.',
    thumbnail: 'https://picsum.photos/seed/ai/800/600',
    gallery: [
      'https://picsum.photos/seed/ai1/800/600',
      'https://picsum.photos/seed/ai2/800/600',
    ],
    demoUrl: 'https://lumina-ai.site/demo',
    liveUrl: 'https://lumina-ai.site',
    category: 'AI',
    tags: ['Stable Diffusion', 'Python', 'React'],
    techStack: ['React', 'Python', 'FastAPI', 'PyTorch', 'AWS GPU'],
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Connect - Enterprise Chat App',
    shortDescription: 'Secure, real-time communication for distributed teams.',
    fullDescription: 'Connect offers zero-knowledge encryption for corporate messaging. Featuring thread organization, file sharing integration, and deep search capabilities.',
    thumbnail: 'https://picsum.photos/seed/chat/800/600',
    gallery: [
      'https://picsum.photos/seed/chat1/800/600',
    ],
    liveUrl: 'https://connect-chat.com',
    category: 'SaaS',
    tags: ['WebSockets', 'End-to-End Encryption'],
    techStack: ['React', 'Socket.io', 'PostgreSQL', 'Docker', 'Redis'],
    isFeatured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'The Minimalist Portfolio',
    shortDescription: 'A ultra-fast, SEO-optimized personal portfolio for creatives.',
    fullDescription: 'A masterclass in modern web design. Zero-JS initial load, 100 Lighthouse score, and a focus on beautiful typography and smooth scroll animations.',
    thumbnail: 'https://picsum.photos/seed/portfolio/800/600',
    gallery: [
      'https://picsum.photos/seed/port1/800/600',
    ],
    liveUrl: 'https://minimalist-portfolio.dev',
    category: 'Website',
    tags: ['Astro', 'Tailwind', 'UX'],
    techStack: ['Astro', 'Markdown', 'Tailwind CSS', 'Vercel'],
    isFeatured: false,
    createdAt: new Date().toISOString(),
  },
];
